import React, { useState, useEffect, useRef } from 'react';
import {
  ChevronLeft, ChevronRight, Maximize2, Minimize2, Play, Pause,
  History, Palette, Sparkles, TrendingUp, Grid, Quote, Layout,
  Layers, MessageSquare, Clock
} from 'lucide-react';

function safeStr(val, fallback = '') {
  if (val == null) return fallback;
  if (typeof val === 'string' || typeof val === 'number') return String(val);
  if (typeof val === 'object') return val.title || val.name || val.text || val.label || val.value || JSON.stringify(val);
  return String(val);
}

export default function SlidePlayer({
  blocks = [],
  artifactId,
  token,
  onOpenHistory
}) {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [isPlaying, setIsPlaying] = useState(false);
  const [showNotes, setShowNotes] = useState(false);
  const autoplayTimerRef = useRef(null);

  // ── Parse & Classify Slide Content Dynamically ──
  const parseSlide = (b, index) => {
    let parsed = {};
    const raw = String(b.content || '').trim();

    try {
      parsed = JSON.parse(raw);
    } catch {
      // Parse markdown content
      const lines = raw.split('\n').map(l => l.trim()).filter(Boolean);
      const bullets = [];
      let subtitle = '';
      let quoteText = '';

      lines.forEach(line => {
        if (line.startsWith('- ') || line.startsWith('* ') || line.startsWith('• ')) {
          bullets.push(line.slice(2).trim());
        } else if (/^\d+\.\s/.test(line)) {
          bullets.push(line.replace(/^\d+\.\s*/, '').trim());
        } else if (line.startsWith('> ')) {
          quoteText = line.slice(2).trim();
        } else if (!subtitle && !line.startsWith('#')) {
          subtitle = line;
        } else {
          bullets.push(line);
        }
      });

      parsed = {
        title: b.title || `Slide ${index + 1}`,
        subtitle,
        bullets,
        quote: quoteText,
        notes: ''
      };
    }

    const title = safeStr(parsed.title || b.title, `Slide ${index + 1}`);
    const subtitle = safeStr(parsed.subtitle || parsed.tagline, '');
    const rawBullets = Array.isArray(parsed.bullets)
      ? parsed.bullets
      : Array.isArray(parsed.content)
        ? parsed.content
        : typeof parsed.content === 'string'
          ? [parsed.content]
          : [];
    const bullets = rawBullets.map((bItem) => safeStr(bItem));
    const notes = safeStr(parsed.notes || parsed.speaker_notes, '');
    const steps = (Array.isArray(parsed.steps) ? parsed.steps : Array.isArray(parsed.timeline) ? parsed.timeline : []).map(s => typeof s === 'object' && s !== null ? { ...s, title: safeStr(s.title || s.name || s.step), desc: safeStr(s.desc || s.description || s.text) } : { title: safeStr(s), desc: '' });
    const columns = Array.isArray(parsed.columns) ? parsed.columns : [];
    const badge = safeStr(parsed.badge || parsed.tag, (index === 0 ? 'Keynote' : ''));
    const author = safeStr(parsed.author, '');
    const role = safeStr(parsed.role, '');
    const customHtml = parsed.html || parsed.custom_html || (raw.startsWith('<') ? raw : '');

    // Dynamic styles generated by LLM
    const theme = {
      bg: parsed.background || parsed.bg || parsed.theme?.bg || 'radial-gradient(circle at 50% 25%, #1e1b4b 0%, #090d16 100%)',
      accent: parsed.accent_color || parsed.accent || parsed.theme?.accent || '#818cf8',
      cardBg: parsed.card_bg || parsed.theme?.cardBg || 'rgba(255, 255, 255, 0.05)',
      cardBorder: parsed.card_border || parsed.theme?.cardBorder || 'rgba(129, 140, 248, 0.25)',
      text: parsed.text_color || parsed.theme?.text || '#ffffff',
      subtext: parsed.subtext_color || parsed.theme?.subtext || '#cbd5e1'
    };

    // ── Auto-Detect Optimal Layout ──
    let layout = parsed.layout || '';
    if (!layout) {
      if (customHtml) {
        layout = 'custom_html';
      } else if (steps.length > 0) {
        layout = 'timeline';
      } else if (columns.length > 0) {
        layout = 'split';
      } else if (index === 0 && bullets.length <= 1 && !parsed.stats?.length && !parsed.cards?.length) {
        layout = 'hero';
      } else if (parsed.stats?.length > 0 || bullets.some(b => /\b(\$?\d+[\d,\.]*[%kMGBx\+]*)\b/.test(String(b)))) {
        layout = 'stats';
      } else if (parsed.quote || (bullets.length === 1 && bullets[0].length > 80 && bullets[0].startsWith('"'))) {
        layout = 'quote';
      } else if (parsed.cards?.length > 0 || bullets.length >= 4) {
        layout = 'grid';
      } else if (bullets.length === 2 || bullets.length === 3) {
        layout = 'split';
      } else {
        layout = 'standard';
      }
    }

    return {
      title,
      subtitle,
      bullets,
      notes,
      stats: parsed.stats || [],
      cards: parsed.cards || [],
      steps,
      columns,
      badge,
      author,
      role,
      quote: parsed.quote || '',
      customHtml,
      theme,
      layout,
      block_key: b.block_key
    };
  };

  const slides = blocks.length > 0
    ? blocks.map((b, idx) => parseSlide(b, idx))
    : [{ title: 'Dynamic Slide Presentation', subtitle: 'AI Designed Presentation Deck', bullets: ['Custom layout', 'Dynamic theme colors'], layout: 'hero', block_key: 'slide_1', theme: { bg: 'radial-gradient(circle at 50% 25%, #1e1b4b 0%, #090d16 100%)', accent: '#818cf8', cardBg: 'rgba(255,255,255,0.05)', cardBorder: 'rgba(129,140,248,0.25)', text: '#ffffff', subtext: '#cbd5e1' } }];

  const currentSlide = slides[currentIndex] || slides[0];
  const theme = currentSlide.theme || {
    bg: 'radial-gradient(circle at 50% 25%, #1e1b4b 0%, #090d16 100%)',
    accent: '#818cf8',
    cardBg: 'rgba(255, 255, 255, 0.05)',
    cardBorder: 'rgba(129, 140, 248, 0.25)',
    text: '#ffffff',
    subtext: '#cbd5e1'
  };

  // ── Autoplay Loop ──
  useEffect(() => {
    if (isPlaying) {
      autoplayTimerRef.current = setInterval(() => {
        setCurrentIndex((prev) => {
          if (prev >= slides.length - 1) {
            setIsPlaying(false);
            return prev;
          }
          return prev + 1;
        });
      }, 4500);
    } else {
      if (autoplayTimerRef.current) clearInterval(autoplayTimerRef.current);
    }
    return () => {
      if (autoplayTimerRef.current) clearInterval(autoplayTimerRef.current);
    };
  }, [isPlaying, slides.length]);

  // ── Keyboard Navigation ──
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'ArrowRight' || e.key === ' ') {
        setCurrentIndex((i) => Math.min(slides.length - 1, i + 1));
      } else if (e.key === 'ArrowLeft') {
        setCurrentIndex((i) => Math.max(0, i - 1));
      } else if (e.key === 'f' || e.key === 'F') {
        setIsFullscreen(f => !f);
      } else if (e.key === 'Escape' && isFullscreen) {
        setIsFullscreen(false);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [slides.length, isFullscreen]);

  // ── Render Slide Layout Dynamically ──
  const renderSlideContent = () => {
    switch (currentSlide.layout) {
      case 'custom_html':
        return (
          <div
            className="slide-layout-custom-html"
            style={{ width: '100%', height: '100%', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}
            dangerouslySetInnerHTML={{ __html: currentSlide.customHtml }}
          />
        );

      case 'hero':
        return (
          <div className="slide-layout-hero">
            <div className="slide-badge-pill" style={{ borderColor: theme.accent, color: theme.accent }}>
              <Sparkles size={12} /> {currentSlide.badge || 'Keynote Presentation'}
            </div>
            <h1 className="slide-hero-title">{currentSlide.title}</h1>
            {currentSlide.subtitle && (
              <p className="slide-hero-subtitle" style={{ color: theme.subtext }}>
                {currentSlide.subtitle}
              </p>
            )}
            {currentSlide.bullets.length > 0 && (
              <div className="slide-hero-bullets">
                {currentSlide.bullets.map((b, idx) => (
                  <span key={idx} className="slide-hero-tag" style={{ background: theme.cardBg, borderColor: theme.cardBorder }}>
                    {b}
                  </span>
                ))}
              </div>
            )}
          </div>
        );

      case 'stats':
        return (
          <div className="slide-layout-stats">
            <h2 className="slide-section-title">{currentSlide.title}</h2>
            {currentSlide.subtitle && <p className="slide-section-subtitle" style={{ color: theme.subtext }}>{currentSlide.subtitle}</p>}
            <div className="slide-stats-grid">
              {(currentSlide.stats.length > 0 ? currentSlide.stats : currentSlide.bullets).map((st, idx) => {
                const isObj = typeof st === 'object' && st !== null;
                const value = isObj ? st.value : (String(st).match(/\b(\$?\d+[\d,\.]*[%kMGBx\+]*)\b/) ? String(st).match(/\b(\$?\d+[\d,\.]*[%kMGBx\+]*)\b/)[0] : `${idx + 1}`);
                const label = isObj ? st.label : String(st).replace(value, '').replace(/^[:\-\s]+/, '');
                const change = isObj ? st.change : '';

                return (
                  <div key={idx} className="slide-stat-card" style={{ background: theme.cardBg, borderColor: theme.cardBorder }}>
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', width: '100%' }}>
                      <div className="slide-stat-icon" style={{ color: theme.accent }}>
                        <TrendingUp size={18} />
                      </div>
                      {change && (
                        <span style={{ fontSize: '10.5px', fontWeight: 700, color: '#34d399', background: 'rgba(52, 211, 153, 0.15)', padding: '1px 6px', borderRadius: '4px' }}>
                          {change}
                        </span>
                      )}
                    </div>
                    <div className="slide-stat-value" style={{ color: theme.accent }}>
                      {value}
                    </div>
                    <div className="slide-stat-label" style={{ color: theme.subtext }}>
                      {label || st}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        );

      case 'timeline':
      case 'process':
        return (
          <div className="slide-layout-timeline">
            <h2 className="slide-section-title">{currentSlide.title}</h2>
            {currentSlide.subtitle && <p className="slide-section-subtitle" style={{ color: theme.subtext }}>{currentSlide.subtitle}</p>}
            <div className="slide-timeline-container">
              {(currentSlide.steps.length > 0 ? currentSlide.steps : currentSlide.bullets).map((step, idx) => {
                const isObj = typeof step === 'object' && step !== null;
                const stepLabel = isObj ? (step.step || `Step ${idx + 1}`) : `0${idx + 1}`;
                const stepTitle = isObj ? step.title : step;
                const stepDesc = isObj ? (step.desc || step.description) : '';

                return (
                  <div key={idx} className="slide-timeline-item" style={{ background: theme.cardBg, borderColor: theme.cardBorder }}>
                    <div className="slide-timeline-badge" style={{ background: theme.accent, color: '#090d16' }}>
                      {stepLabel}
                    </div>
                    <div className="slide-timeline-content">
                      <div className="slide-timeline-step-title">{stepTitle}</div>
                      {stepDesc && <div className="slide-timeline-step-desc" style={{ color: theme.subtext }}>{stepDesc}</div>}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        );

      case 'grid':
      case 'matrix':
        return (
          <div className="slide-layout-grid">
            <h2 className="slide-section-title">{currentSlide.title}</h2>
            {currentSlide.subtitle && <p className="slide-section-subtitle" style={{ color: theme.subtext }}>{currentSlide.subtitle}</p>}
            <div className="slide-cards-matrix">
              {(currentSlide.cards.length > 0 ? currentSlide.cards : currentSlide.bullets).map((card, idx) => {
                const isObj = typeof card === 'object' && card !== null;
                const cardTitle = isObj ? card.title : card;
                const cardDesc = isObj ? card.description : '';
                const cardBadge = isObj ? card.badge : '';

                return (
                  <div key={idx} className="slide-matrix-card" style={{ background: theme.cardBg, borderColor: theme.cardBorder }}>
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', width: '100%', marginBottom: '8px' }}>
                      <div className="slide-card-num" style={{ background: theme.accent, color: '#090d16' }}>
                        {idx + 1}
                      </div>
                      {cardBadge && (
                        <span style={{ fontSize: '10px', fontWeight: 650, color: theme.accent, background: 'rgba(255, 255, 255, 0.08)', padding: '2px 6px', borderRadius: '4px' }}>
                          {cardBadge}
                        </span>
                      )}
                    </div>
                    <div className="slide-card-heading">{cardTitle}</div>
                    {cardDesc && <div className="slide-card-desc" style={{ color: theme.subtext }}>{cardDesc}</div>}
                  </div>
                );
              })}
            </div>
          </div>
        );

      case 'split':
      case 'comparison':
        if (currentSlide.columns && currentSlide.columns.length > 0) {
          return (
            <div className="slide-layout-split">
              <div style={{ width: '100%', textAlign: 'center', marginBottom: '16px' }}>
                <h2 className="slide-split-title">{currentSlide.title}</h2>
                {currentSlide.subtitle && <p className="slide-split-subtitle" style={{ color: theme.subtext }}>{currentSlide.subtitle}</p>}
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: `repeat(${currentSlide.columns.length}, 1fr)`, gap: '16px', width: '100%' }}>
                {currentSlide.columns.map((col, idx) => (
                  <div key={idx} className="slide-feature-box" style={{ background: theme.cardBg, borderColor: theme.cardBorder, textAlign: 'left', alignItems: 'flex-start' }}>
                    <h3 style={{ margin: '0 0 10px 0', fontSize: '16px', color: theme.accent }}>{col.title}</h3>
                    <div className="slide-split-bullets">
                      {(col.items || []).map((it, itIdx) => (
                        <div key={itIdx} className="slide-bullet-row">
                          <span className="slide-bullet-dot" style={{ background: theme.accent }} />
                          <span style={{ color: theme.text }}>{it}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          );
        }

        return (
          <div className="slide-layout-split">
            <div className="slide-split-left">
              <h2 className="slide-split-title">{currentSlide.title}</h2>
              {currentSlide.subtitle && <p className="slide-split-subtitle" style={{ color: theme.subtext }}>{currentSlide.subtitle}</p>}
              <div className="slide-split-bullets">
                {currentSlide.bullets.map((b, idx) => (
                  <div key={idx} className="slide-bullet-row">
                    <span className="slide-bullet-dot" style={{ background: theme.accent }} />
                    <span style={{ color: theme.text }}>{b}</span>
                  </div>
                ))}
              </div>
            </div>
            <div className="slide-split-right">
              <div className="slide-feature-box" style={{ background: theme.cardBg, borderColor: theme.cardBorder }}>
                <Sparkles size={24} style={{ color: theme.accent, marginBottom: '12px' }} />
                <div className="slide-feature-text" style={{ color: theme.subtext }}>
                  {currentSlide.bullets[0] || currentSlide.title}
                </div>
              </div>
            </div>
          </div>
        );

      case 'quote':
      case 'callout':
        return (
          <div className="slide-layout-quote">
            <Quote size={36} style={{ color: theme.accent, opacity: 0.8, marginBottom: '16px' }} />
            <blockquote className="slide-quote-text">
              "{currentSlide.quote || currentSlide.bullets[0] || currentSlide.title}"
            </blockquote>
            {(currentSlide.author || currentSlide.subtitle) && (
              <div className="slide-quote-author" style={{ color: theme.accent }}>
                — {currentSlide.author || currentSlide.subtitle} {currentSlide.role ? `(${currentSlide.role})` : ''}
              </div>
            )}
          </div>
        );

      case 'standard':
      default:
        return (
          <div className="slide-layout-standard">
            <h2 className="slide-section-title">{currentSlide.title}</h2>
            {currentSlide.subtitle && <p className="slide-section-subtitle" style={{ color: theme.subtext }}>{currentSlide.subtitle}</p>}
            <ul className="slide-standard-list">
              {currentSlide.bullets.map((b, idx) => (
                <li key={idx} style={{ color: theme.text }}>
                  <span className="slide-bullet-point" style={{ background: theme.accent }} />
                  <span>{b}</span>
                </li>
              ))}
            </ul>
          </div>
        );
    }
  };

  return (
    <div className={`slide-player-container ${isFullscreen ? 'is-fullscreen' : ''}`}>
      {/* ── Slide Stage Viewport ── */}
      <div
        className="slide-canvas"
        style={{
          background: theme.bg,
          transition: 'background 0.35s ease'
        }}
      >
        {/* Top Floating Action Bar */}
        <div className="slide-top-actions">
          {currentSlide.notes && (
            <button
              className={`canvas-btn ${showNotes ? 'canvas-btn-primary' : 'canvas-btn-secondary'}`}
              style={{ fontSize: '11px', padding: '4px 8px' }}
              onClick={() => setShowNotes(!showNotes)}
              title="Toggle Speaker Notes"
            >
              <MessageSquare size={12} /> Notes
            </button>
          )}

          <button
            className="canvas-btn canvas-btn-secondary"
            style={{ fontSize: '11px', padding: '4px 8px' }}
            onClick={() => onOpenHistory && onOpenHistory(currentSlide.block_key, currentSlide.title)}
            title="Inspect Slide Revisions"
          >
            <History size={12} /> History
          </button>

          <button
            className="canvas-btn canvas-btn-secondary"
            style={{ padding: '4px 8px' }}
            onClick={() => setIsFullscreen(!isFullscreen)}
            title={isFullscreen ? 'Exit Fullscreen (Esc)' : 'Fullscreen (F)'}
          >
            {isFullscreen ? <Minimize2 size={13} /> : <Maximize2 size={13} />}
          </button>
        </div>

        {/* Dynamic Slide Content */}
        <div className="slide-dynamic-content">
          {renderSlideContent()}
        </div>

        {/* Slide Progress Indicator Bar */}
        <div className="slide-bottom-bar">
          <span className="slide-layout-pill" style={{ color: theme.subtext }}>
            <Layers size={10} style={{ marginRight: '4px' }} />
            {currentSlide.layout.toUpperCase()}
          </span>
          <div className="slide-step-dots">
            {slides.map((_, i) => (
              <span
                key={i}
                className={`slide-step-dot ${i === currentIndex ? 'active' : ''}`}
                style={{ background: i === currentIndex ? theme.accent : 'rgba(255,255,255,0.2)' }}
                onClick={() => setCurrentIndex(i)}
              />
            ))}
          </div>
          <span style={{ fontSize: '11px', color: theme.subtext, fontWeight: 600 }}>
            {currentIndex + 1} / {slides.length}
          </span>
        </div>
      </div>

      {/* ── Speaker Notes Drawer ── */}
      {showNotes && currentSlide.notes && (
        <div className="slide-notes-drawer" style={{ background: theme.cardBg, borderColor: theme.cardBorder }}>
          <div className="slide-notes-header">
            <MessageSquare size={13} style={{ color: theme.accent }} /> Speaker Notes
          </div>
          <div className="slide-notes-body" style={{ color: theme.subtext }}>
            {currentSlide.notes}
          </div>
        </div>
      )}

      {/* ── Interactive Player Navigation Toolbar ── */}
      <div className="slide-controls">
        <button
          className="canvas-btn canvas-btn-secondary"
          disabled={currentIndex === 0}
          onClick={() => setCurrentIndex((i) => Math.max(0, i - 1))}
        >
          <ChevronLeft size={16} /> Prev
        </button>

        <button
          className={`canvas-btn ${isPlaying ? 'canvas-btn-primary' : 'canvas-btn-secondary'}`}
          onClick={() => setIsPlaying(!isPlaying)}
          title={isPlaying ? 'Pause Autoplay' : 'Start Autoplay Presentation'}
        >
          {isPlaying ? <Pause size={14} /> : <Play size={14} />}
          {isPlaying ? 'Pause' : 'Autoplay'}
        </button>

        <button
          className="canvas-btn canvas-btn-secondary"
          disabled={currentIndex >= slides.length - 1}
          onClick={() => setCurrentIndex((i) => Math.min(slides.length - 1, i + 1))}
        >
          Next <ChevronRight size={16} />
        </button>
      </div>

      {/* ── Interactive Slide Deck Thumbnail Strip ── */}
      <div className="slide-thumbnails-strip">
        {slides.map((s, idx) => (
          <button
            key={idx}
            onClick={() => setCurrentIndex(idx)}
            className={`slide-thumb-card ${idx === currentIndex ? 'active' : ''}`}
            style={{
              borderColor: idx === currentIndex ? theme.accent : 'rgba(255,255,255,0.08)'
            }}
          >
            <div className="slide-thumb-num">{idx + 1}</div>
            <div className="slide-thumb-title">{s.title}</div>
            <div className="slide-thumb-type">{s.layout}</div>
          </button>
        ))}
      </div>
    </div>
  );
}

